name: Continuous integration

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - uses: actions/checkout@v4
      - run: deno test # TODO: Coverage report
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - uses: actions/checkout@v4
      - run: deno fmt --check
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - uses: actions/checkout@v4
      - run: deno lint
