name: Run linter

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - uses: actions/checkout@v4
      - run: deno lint
